Repository JCSDA/spack-stack, pull requests merged in 2024-05, with the labels that each got.

#1096 Make Casper a Tier2 platform
  doc/source/PreConfiguredSites.rst
Labels: INFRA, OAR-EPIC

#1089 Update upp-env packages
  spack-ext/repos/spack-stack/packages/upp-env/package.py
Labels: NOAA-EMC

#1107 Fix formatting of configs/sites/noaa-*/README.md
  configs/sites/noaa-aws/README.md
  configs/sites/noaa-azure/README.md
  configs/sites/noaa-gcloud/README.md
Labels: INFRA, OAR-EPIC

#1108 Update KnownIssues.rst with solution for bad oneAPI `libirc.so`
  doc/source/KnownIssues.rst
Labels: INFRA

#1099 JEDI CI container specs update and FMS update for JEDI-FV3
  configs/containers/docker-ubuntu-intel-impi.yaml
  configs/containers/specs/jedi-ci.yaml
  spack-ext/repos/spack-stack/packages/gmao-swell-env/package.py
  spack-ext/repos/spack-stack/packages/jedi-fv3-env/package.py
Labels: INFRA

#1111 Add gcc stack for Nautilus
  configs/sites/nautilus/compilers.yaml
  configs/sites/nautilus/packages.yaml
Labels: NAVY

#1114 fix a couple bugs in util/check_package_config.py
  util/check_package_config.py
Labels: NOAA-EMC

#1103 Add NEPTUNE standalone virtual package and template, add Atlantis site config
  .github/workflows/ubuntu-ci-x86_64-intel.yaml
  configs/common/packages.yaml
  configs/sites/atlantis/compilers.yaml
  configs/sites/atlantis/config.yaml
  configs/sites/atlantis/modules.yaml
  configs/sites/atlantis/packages.yaml
  configs/templates/neptune-dev/spack.yaml
  spack-ext/repos/spack-stack/packages/jedi-neptune-env/package.py
  spack-ext/repos/spack-stack/packages/neptune-env/package.py
Labels: NAVY
