Repository JCSDA/spack-stack, pull requests merged in 2024-12, with the labels that each got.

#1394 Build ip with gcc when using aocc as preferred compiler, bump ip to 5.1.0
  configs/common/packages.yaml
  configs/common/packages_aocc.yaml
  configs/sites/tier2/blackpearl/packages_aocc.yaml
  spack-ext/repos/spack-stack/packages/neptune-env/package.py
Labels: enhancement

#1403 Bump ip to 5.1.0 in JEDI CI container specs
  configs/containers/specs/jedi-ci.yaml
Labels: INFRA

#1420 [skip ci] Clarify instructions about the python version that is being used to create a new local environment
  doc/source/PreConfiguredSites.rst
Labels: INFRA

#1430 Downgrade ectrans version 1.5.0 to version 1.2.0
  configs/common/packages.yaml
  configs/containers/specs/jedi-ci.yaml
  configs/sites/tier1/acorn/packages_intel.yaml
  configs/sites/tier1/aws-pcluster/packages_intel.yaml
  configs/sites/tier1/gaea-c5/packages.yaml
  configs/sites/tier1/gaea-c6/packages.yaml
  configs/sites/tier1/hera/packages_intel.yaml
  configs/sites/tier1/hercules/packages_intel.yaml
  configs/sites/tier1/nautilus/packages_aocc.yaml
  configs/sites/tier1/nautilus/packages_gcc.yaml
  configs/sites/tier1/noaa-aws/packages_intel.yaml
  configs/sites/tier1/noaa-azure/packages_intel.yaml
  configs/sites/tier1/noaa-gcloud/packages_intel.yaml
  configs/sites/tier1/orion/packages_intel.yaml
  configs/sites/tier1/s4/packages.yaml
Labels: INFRA

#1429 Fix container builds after #1384
  configs/containers/specs/jedi-ci.yaml
Labels: INFRA

#1427 Update KnownIssues.rst: python on Cray is non-functional: Could not find platform dependent libraries <exec_prefix>
  doc/source/KnownIssues.rst
Labels: documentation
