Repository JCSDA/spack-stack, pull requests merged in 2024-09, with the labels that each got.

#1280 release/1.8.0: Update site configs for Nautilus, Blackpearl, Casper; move release-specific site documentation for preconfigured sites to Wiki
  configs/common/packages_aocc.yaml
  configs/sites/tier1/atlantis/compilers.yaml
  configs/sites/tier1/atlantis/modules.yaml
  configs/sites/tier1/narwhal/modules.yaml
  configs/sites/tier1/narwhal/packages.yaml
  configs/sites/tier1/nautilus/compilers.yaml
  configs/sites/tier1/nautilus/modules.yaml
  configs/sites/tier1/nautilus/packages.yaml
  configs/sites/tier1/nautilus/packages_aocc.yaml
  configs/sites/tier1/nautilus/packages_oneapi.yaml
  configs/sites/tier1/sandy/modules.yaml
  configs/sites/tier2/blackpearl/compilers.yaml
  configs/sites/tier2/blackpearl/packages_oneapi.yaml
  configs/sites/tier2/casper/compilers.yaml
  configs/sites/tier2/casper/config.yaml
  configs/sites/tier2/casper/mirrors.yaml
  configs/sites/tier2/casper/modules.yaml
  configs/sites/tier2/casper/packages.yaml
  doc/source/PreConfiguredSites.rst
  spack-ext/repos/spack-stack/packages/neptune-env/package.py
Labels: documentation

#1298 release/1.8.0: next round of NRL site config/doc updates
  configs/sites/tier1/atlantis/packages_oneapi.yaml
  doc/source/PreConfiguredSites.rst
Labels: NAVY

#1307 Add site config for tier2 machine bounty and update doc/source/NewSiteConfigs.rst for Ubuntu
  configs/sites/tier2/blackpearl/README.md
  configs/sites/tier2/bounty/README.md
  configs/sites/tier2/bounty/compilers.yaml
  configs/sites/tier2/bounty/config.yaml
  configs/sites/tier2/bounty/mirrors.yaml
  configs/sites/tier2/bounty/modules.yaml
  configs/sites/tier2/bounty/packages.yaml
  configs/sites/tier2/bounty/packages_gcc.yaml
  doc/source/NewSiteConfigs.rst
Labels: NAVY

#1306 update for discover-scu17 mkl and docs
  configs/sites/tier1/discover-scu17/packages_intel.yaml
  doc/source/PreConfiguredSites.rst
Labels: INFRA, ready for merge

#1311 Adding py-ruamel modules for gmao-swell-env
  configs/common/packages.yaml
  spack-ext/repos/spack-stack/packages/gmao-swell-env/package.py
Labels: INFRA
