Repository JCSDA/spack-stack, pull requests merged in 2024-10, with the labels that each got.

#1328 For release/1.8.0: update S4 site config and documentation
  configs/sites/tier1/s4/compilers.yaml
  configs/sites/tier1/s4/packages.yaml
  doc/source/PreConfiguredSites.rst
Labels: INFRA

#1334 Update PreConfiguredSites.rst - remove outdated comment for Derecho
  doc/source/PreConfiguredSites.rst
Labels: documentation

#1335 update documentation for module soft links
  doc/source/PreConfiguredSites.rst
Labels: documentation

#1346 Remove LaTeX documentation from readthedocs
  doc/CMakeLists.txt
  doc/requirements.txt
  doc/source/NewSiteConfigs.rst
  doc/source/conf.py
Labels: documentation

#1343 Move NEPTUNE Python dependencies into its their own package neptune-python-env, remove legacy environment variables for NEPTUNE
  configs/common/modules_lmod.yaml
  configs/common/modules_tcl.yaml
  configs/templates/neptune-dev/spack.yaml
  configs/templates/skylab-dev/spack.yaml
  configs/templates/unified-dev/spack.yaml
  spack-ext/repos/spack-stack/packages/neptune-env/package.py
  spack-ext/repos/spack-stack/packages/neptune-python-env/package.py
Labels: NAVY

#1353 [skip ci] Bug fix for wrong local-source paths on Narwhal and Nautilus
  configs/sites/tier1/narwhal/mirrors.yaml
  configs/sites/tier1/nautilus/mirrors.yaml
Labels: bug
