Repository JCSDA/spack-stack, pull requests merged in 2024-06, with the labels that each got.

#1132 Add gaea c6 config
  configs/sites/gaea-c6/compilers.yaml
  configs/sites/gaea-c6/config.yaml
  configs/sites/gaea-c6/mirrors.yaml
  configs/sites/gaea-c6/modules.yaml
  configs/sites/gaea-c6/packages.yaml
Labels: NOAA-EMC

#1151 Support multiple esmf versions in unified environment / updates of neptune-dev, unified-dev, skylab-dev templates (add `%oneapi`)
  .github/workflows/macos-ci-aarch64.yaml
  .github/workflows/ubuntu-ci-x86_64-gnu.yaml
  .github/workflows/ubuntu-ci-x86_64-intel.yaml
  configs/common/packages.yaml
  configs/sites/atlantis/packages.yaml
  configs/templates/neptune-dev/spack.yaml
  configs/templates/skylab-dev/spack.yaml
  configs/templates/unified-dev/spack.yaml
Labels: INFRA, NOAA-EMC, OAR-EPIC, NAVY

#1150 Fix broken JEDI container builds after updating ESMF and MAPL to 8.6.1/2.46.2
  configs/containers/specs/jedi-ci.yaml
Labels: INFRA

#1172 Update flex version to 2.6.4 in the discover scu16 config
  configs/sites/discover-scu16/packages.yaml
Labels: INFRA
