Repository JCSDA/spack-stack, pull requests merged in 2025-02, with the labels that each got.

#1489 develop: Update NRL batch install script, add configuration for Cole and Tusk
  configs/sites/tier1/blueback/mirrors.yaml
  configs/sites/tier2/cole/compilers.yaml
  configs/sites/tier2/cole/config.yaml
  configs/sites/tier2/cole/mirrors.yaml
  configs/sites/tier2/cole/modules.yaml
  configs/sites/tier2/cole/packages.yaml
  configs/sites/tier2/cole/packages_gcc.yaml
  configs/sites/tier2/cole/packages_oneapi.yaml
  configs/sites/tier2/tusk/compilers.yaml
  configs/sites/tier2/tusk/config.yaml
  configs/sites/tier2/tusk/mirrors.yaml
  configs/sites/tier2/tusk/modules.yaml
  configs/sites/tier2/tusk/packages.yaml
  configs/sites/tier2/tusk/packages_gcc.yaml
  configs/sites/tier2/tusk/packages_oneapi.yaml
  configs/templates/neptune-dev/spack.yaml
  doc/source/PreConfiguredSites.rst
  util/nrl/batch_install.sh
Labels: NAVY

#1498 Update util/weekly_build/03_SetupEnv.sh: exclude crtm-fix from check for duplicates
  util/weekly_build/03_SetupEnv.sh
Labels: bug

#1517 Updates for discover 1.9.0 configs
  configs/sites/tier1/discover-scu17/compilers.yaml
  configs/sites/tier1/discover-scu17/packages_intel.yaml
  configs/sites/tier1/discover-scu17/packages_oneapi.yaml
Labels: INFRA
